import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/utils/Providers";
import { FolderProvider } from "./context/FolderProvider";
const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Fiing | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <FolderProvider>
          {children}
          </FolderProvider>
        </Providers>
      </body>
    </html>
  );
}
